### ISSUE TITLE
Threads aren't working?

### ISSUE THREAD

**Issue by isakgrozny** [y-lohse/inkjs#11]
Testing a story of mine, [threads](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#2-threads) don't seem to be working -- no choices appear, even though choices are supposed to be gathered from the threaded nodes.

It works in Inklecate's command-line player, so it's not an issue with my code.

**Comment by y-lohse** [comment]
Hello,
I just ran the example from the doc, and it appears to be working. Are you sure you're using the latest version of inkjs (0.9.0)? There have been quite a few updates lately.
Otherwise, can you provide me an example of a non-working ink file that I can test?

**Comment by isakgrozny** [comment]
I think the issue is that I'm using === and =, while the example uses ==? [Here is the JSON file that's not working.](https://gist.github.com/isakgrozny/51d96c95849a6e78c81721742c57215c)

**Comment by isakgrozny** [comment]
Okay, I think I may have figured out what's going on -- InkJS currently can't deal with multiple threading calls in a row; after gathering the first call's choices, if it sees another thread stack, it assumes the thread can still be popped and throws an error.

Here's the code that's doing it (I think):

```
// Finished a section of content / reached a choice point?
			if (!this.canContinue) {

				if (this.state.callStack.canPopThread) {
					throw "Thread available to pop, threads should always be flat by the end of evaluation?";
				}
```

**Comment by y-lohse** [comment]
More or less, yes. However this behavior is not a limitation of inkjs, it's how things are supposed to work.

But I also ran your ink using inklecate, and the results are different, so there is clearly a bug somewhere. I'll have to take a look with a proper debugger to understand what's going on.

**Comment by y-lohse** [comment]
I just did, but it's a bit hard to track down to be honest, as there are lots of things happening.

Can you maybe try to reproduce the problem with a smaller test file? I can try to isolate it myself if you want, I'd just need the original ink file.

**Comment by isakgrozny** [comment]
It might also be that different versions of Inklecate handle this differently -- I'm on OSX and using the inklecate file provided in the latest ink release, not one compiled from the freshest ink changes. 

[Here is the smallest test case file I could come up with that still features all the functionality I'm trying to get.](https://gist.github.com/isakgrozny/bbed5b44199978386befae9ecec23ff8)

**Comment by isakgrozny** [comment]
[And here's the original ink file.](https://gist.github.com/isakgrozny/4165001829c5c2fcd651bc7d6bf8589f) I forgot that initially, sorry.

**Comment by y-lohse** [comment]
Great, thank you. i'll try to figure out what's happening there, probably later today.

**Comment by y-lohse** [comment]
After a bit of testing, I've boiled the problem down to this:

```
<- thread1
-> END

= thread1
<- thread2

= thread2
* choice
```

If on line 1 I call thread2 instead of thread1, it works, but calling a thread that itself calls another thread causes the `Thread available to pop` error.
I'm not sure if that's what is supposed to happen. Maybe @joethephish can tell us, or I'll do some more tests.

**Comment by isakgrozny** [comment]
I think it's not supposed to happen, as the thread examples in the docs call threads that call threads. But I'm unsure.

**Comment by y-lohse** [comment]
I don't think so either, but it's hard to tell. Here's what's happening:

1. All threads are followed properly
2. The code reaches the choice point, and processes it. At this point there are 3 threads in the callstack.
3. `NextContent` is called, and the last [thread is popped](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L1081).
4. `NextContent` doesn't get called again, because `state.currentContentObject` is null.
5. Since there are still 2 threads in the callstack, the `Thread available to pop` error is generated

I'm afraid we'll have to wait until @joethephish can shed some light on what is supposed to happen here, and hopefully point me into the right direction.

**Comment by joethephish** [comment]
Sure, I'll take a look when I get a moment! Just getting back to work after
vacation tho, so I'm afraid it may not be for a few days...

**Comment by isakgrozny** [comment]
Any news on fixing this bug? It's a pretty big obstacle for me, because I make heavy use of the threads feature of ink.

**Comment by joethephish** [comment]
Apologies for taking a while to get back to you on this! I'm currently investigating, but taking a brief look at @y-lohse's minimal example, I think it should end up with just just that one choice. Then, the other threads should automatically be dropped when you make the choice.

I'm currently not getting that on the C# implementation, suggesting that it's a bug, but I'll investigate further.

**Comment by joethephish** [comment]
Oops, I found the problem in your minimal example: you were using `-> END` rather than `-> DONE`. Since `-> END` *forcefully* ends the flow, it also *removes any existing generated choices* because the assumption is that the author want to finish the story completely.

If you use `-> DONE`, it correctly added the `* choice` as you would expect.

@y-lohse I'm not reproducing the problem you describe of `state.currentContentObject` being null in the C# version I'm afraid. It correctly managed to call `NextContent` recursively a couple of times until it ended up back at `-> END` / `-> DONE`...

**Comment by y-lohse** [comment]
@joethephish thanks for looking into it. I probably should have been clearer though — I have no reason to suspect a bug in ink It's almost definitely a problem with the js version, but the code behaves as it should and I can't see any glaring errors, so I guess it's more a logic problem somewhere.

I've looked into it some more, replacing the `-> END` with a `-> DONE`. Here are some more notes on what's happening, feel free to point out anything that seems weird.

- `NextContent()` is called several times. The last call before the error happens is with `previousContentObject` being the ChoicePoint inisde `thread2`
- `IncrementContentPointer()` is called and it goes through [the `while` loop](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L1093) a few times

After that, a couple of things happen.

The current container ends up pointing to the `thread2` container.
The ancestor of that container does not have `thread2` as an **indexed** content — it's a **named content**.
Because of that, [`indexInAncestor`](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L1103) results in `-1` and the loop is stopped.

The `currentContentIndex` now equals 1 — [a leftover from the previous `while` loop iteration](https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L1109). But the container has only 1 content, so the `currentObject` is [evaluted to null](https://github.com/y-lohse/inkjs/blob/master/engine/CallStack.js#L17).

Now we're back in `NextContent()`. It detects that it can pop a thread, and does it. However, `state.currentContentObject` is now null (because of the above) and `NextContent()` is not called again.

**Comment by y-lohse** [comment]
So essentially, the code tries to find an index container, but it's actually a named container. As a consequence, `IncrementContentPointer()` returns false and the current element's current object becomes null. Is that the expected behavior?

**Comment by y-lohse** [comment]
Another, hopefully simpler way to look at this:

Assuming we just ran out of content because we finished a thread, we reach [this part of the code](https://github.com/y-lohse/ink/blob/master/ink-engine-runtime/Story.cs#L1446). It will pop the current thread, fine. But now this thread was itself in another thread — it should call `NextContent()` again.

However, I don't understand how this can ever happen. [this condition](https://github.com/y-lohse/ink/blob/master/ink-engine-runtime/Story.cs#L1471) checks that `state.currentContentObject` is not null. But if we just ran out of content, [this line](https://github.com/y-lohse/ink/blob/master/ink-engine-runtime/Story.cs#L1507) essentially forced it to null.

Hopefully this is a bit more digest for you to look at @joethephish. I suspect I'm missing a bit of C# magic somewhere.

**Comment by joethephish** [comment]
Thanks for the further clarification. I'm afraid I've been a bit busy
recently so haven't had a chance to look yet, but hopefully soon!

**Comment by y-lohse** [comment]
No worries, take your time :-). I just investigate every now and then and write down whatever I find here.

**Comment by joethephish** [comment]
Okay, just took a look at the code and your comments. Let me see if I can explain this clearly...!

I think the missing link is that when a thread is popped, the value of `currentContentObject` will change, because we'll be looking at the state in an entirely different thread.

So:

1. `bool successfulPointerIncrement = IncrementContentPointer ();` is false, we enter the condition. At this point `currentContentObject` will be null, as you say.
2. `state.callStack.PopThread ();` is called. The old thread where `currentContentObject` was popped, so whatever thread is next on the stack is looked at, where `currentContentObject` is still valid. (e.g. as we jump from `= thread2` to `= thread1`.
3. `state.currentContentObject != null` then evaluates to true.

Does that make sense?

Maybe double check `currentContentObject`'s property definition, and make sure that the properties within `CallStack` are all correct? (e.g. `currentElement`, the internal `callStack`, and `currentThread`).

**Comment by y-lohse** [comment]
On point as always, thank you @joethephish!

I read the faulty line more than once while investigating and somehow looked past the glaring error. @isakgrozny : I'll be rolling out a new version with the bugfix in the coming minutes. Thanks for the report and if you notice anything else, please let me know!

**Comment by isakgrozny** [comment]
Fantastic! Thank you so, so much!
