### ISSUE TITLE
Tutorial on how to use inkjs?

### ISSUE THREAD

**Issue by pineapplemachine** [y-lohse/inkjs#14]
I'm trying and failing to use inkjs to make a webpage for an ink I wrote. I feel like I must be missing something obvious, and some steps to follow for getting things to a workable state would help to at the very least narrow down why I'm getting the errors that I am.

Thanks!

**Comment by y-lohse** [comment]
Hi,
sure, although I'm not sure how far that tutorial should go. How far along have you gotten? What is blocking you at the moment?

**Comment by pineapplemachine** [comment]
Thanks much for the quick response

I'm trying to make my ink playable in the browser. I copied `simple.html` from the repo and substituted a path to my ink.json file. Using `fetch` to get the contents of a local json file fails because "URL scheme "file" is not supported" and using it to get the contents of a remote json file, hosted on either dropbox on my website, always results in an empty content string. I haven't yet resorted to copying the json string wholesale and I'm hoping to avoid that.

**Comment by pineapplemachine** [comment]
I'm also guessing based on the prominence of `console.log` calls that if I want it to be playable outside the console the legwork is going to be up to me?

**Comment by y-lohse** [comment]
Right, `simple.html` is what I use for debuging, so not ideal :stuck_out_tongue: . A better starting point would be the [pages branch](https://github.com/y-lohse/inkjs/tree/gh-pages), especially [this part](https://github.com/y-lohse/inkjs/blob/gh-pages/index.html#L145).

Regarding the json file loading thing... this is sadly a browser problem. As you've seen, loading a file using the `file://` protocol is not permitted, and I think hosting it on dropbox & co fails because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).

You could load it using a file input (see [this](https://github.com/y-lohse/inkjs/blob/gh-pages/index.html#L151)). Or you could use a relative path [like this](https://github.com/y-lohse/inkjs/blob/gh-pages/index.html#L166), but then you need to run the index.html file using a http server. Or as you said, dumping the json file into the html somewhere.

Hope this helps ;)

**Comment by pineapplemachine** [comment]
Ha, that branch helps especially. Thanks much!

That page on CORS helps clear things up, too - seems it'll work as long as the html page and the json are both hosted on the same domain? I'll have to test shortly.

**Comment by pineapplemachine** [comment]
Found a bug - I have a function that accepts an hour 0-23 and makes a string of it, e.g. `9 AM`. Using the `index.html` you linked to the function is returning strings that look like `AM9`.

``` ink
=== function get_stalk_time ===
    {
    - time == 0:
        ~ return "12 AM."
    - time < 12:
        ~ return "{time} AM"
    - time == 12:
        ~ return "12 PM."
    - else:
        ~ return "{time - 12} PM"
    }
```

I'm using `ink.iife.js`.

**Comment by pineapplemachine** [comment]
I just want to put my ink on a webpage dammit

```
ink.iife.js:4175 Uncaught ReferenceError: tjis is not defined
NextSequenceShuffleIndex @ ink.iife.js:4175
PerformLogicAndFlowControl @ ink.iife.js:3710
Step @ ink.iife.js:3333
ContinueInternal @ ink.iife.js:3191
Continue @ ink.iife.js:3158
continueToNextChoice @ finch.html:191
onChoiceSelect @ finch.html:225
dispatch @ jquery-2.2.4.min.js:3
r.handle @ jquery-2.2.4.min.js:3
```

**Comment by pineapplemachine** [comment]
`+ I {&stay where I am|stay where I am|remain in the shop|remain in the shop|continue to sit|continue to sit|order another coffee|order another coffee}.` is being rendered as `.stay where I amI`

**Comment by pineapplemachine** [comment]
Changing line 3675 from `sb += c.toString();` to `sb = c.toString() + sb;` seems to have fixed the two as-of-yet unfixed comments

**Comment by pineapplemachine** [comment]
Hurrah, it's playable! I need to play with the styling more, and please feel free to borrow the styling that's already done

http://pineapplemachine.com/writing/if/finch.html

**Comment by isakgrozny** [comment]
I've actually been having a similar problem to what's described: the choices appeared on top while the text appeared on the bottom and I couldn't figure out how to fix it. Is that a bug in InkJS or was I doing something wrong?

I was using code used in [this repo](https://git.oreolek.ru/if/inkjs-boilerplate/tree/master) to make the story run, because I couldn't quite figure out how to modify the code from the gh-pages branch.

**Comment by y-lohse** [comment]
Awesome work, thank you! I don't have any complex-ish ink scripts myself to test more advanced features, and I can't be bothered to write a test suite at the moment (though it would undoubtedly be useful!).So yeah, feel free to report any problems here!

@isakgrozny You can compare a playthrough in inkjs and inklecate, and if they are not the same, it's a problem with inkjs. Which at this stage is still quite likely tbh. Thanks for linking that boilerplate, I wasn't aware it existd, very cool!

**Comment by pineapplemachine** [comment]
I was hitting one more issue that was easier to just tweak in my ink than try to narrow down what was causing it. When I had choices that looked like this -

``` ink
* choice a {and|a|sequence}
-> somewhere
* choice b {and|a|sequence}
some text
-> somewhere_else
```

They would be incorrectly displayed like this:

```
* choice a
* choice b and
```

**Comment by pineapplemachine** [comment]
@isakgrozny That isn't a bug with inkjs, it's a peculiarity of how the page in the repo you linked to provides an interface. But from a quick glance it does look like the content should be displaying above the options. Have you modified the `index.html` or `game.coffee` files in any way? It should be very easy to produce the behavior you're describing by reordering a couple of lines in the html file, for example.

**Comment by y-lohse** [comment]
Pfew, ok, I published a new version with the latest fixes. Thanks for the help!
I can't reproduce the choice problem you described above, was it happening on the first run? If so, would you mind checking if it's still there in version 1.0.2?

**Comment by y-lohse** [comment]
I worked on a more complete tutorial [here](https://github.com/y-lohse/inkjs/tree/dev) and I'd love some feedback and pointers to anything else that would have helped you start out :-)

**Comment by joethephish** [comment]
Related to #18, I wonder if it would be better to tell people to wrap their JSON, so that this:

**myStory.json**: `{...}` 

Becomes:

**myStory.js**: `var storyContent = {...};`

...since it doesn't require usage of the new fetch API, which could be off-putting to relative novices? I didn't know that the fetch API existed myself - I had to look it up! Likewise, I was aware of the concept of promises, but I didn't realise that built-in browser support had been added...

**Comment by joethephish** [comment]
Oh, and another downside of the fetch approach is that you have to start a server in order to test it, rather than just previewing by opening a local HTML file, which is pretty bad for novices too. 

Of course, it's pretty crap that they have to hand-edit / copy-paste their JSON file, but that's probably less bad IMHO...

**Comment by y-lohse** [comment]
Yeaaah I suppose that makes sense. It'd be nice to catter for both novices and more experienced front-end devs though, but I'm not sure how to best structure it.

**Comment by pineapplemachine** [comment]
I'd recommend making the link to the source of the demo page within the repo more prominent, and `everything` is misspelled toward the end of the readme

But it generally looks much better. Thanks!

**Comment by joethephish** [comment]
Well, fingers crossed it shouldn't be too much of an issue if novices get into it via Inky, since that way they don't really have to think about it, since it's handled for them. If they're coming to inkjs some other way, we could perhaps assume that they know a little bit more what they're doing...

**Comment by y-lohse** [comment]
I did another round on this issue. The server less approach is now the most heavily featured, there are prominent links to various [templates](https://github.com/y-lohse/inkjs/tree/master/templates) (@joethephish I used your inky template for the browser, hope that's ok) and everything is shorter and hopefully clearer.

**Comment by joethephish** [comment]
Sure, glad the template was helpful! Tutorial is looking really great now btw, really intuitive.
