### ISSUE TITLE
Transform the variable casting

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#177]
At the moment, all `var MyThing as Thing` from the original code are simple assignments, with an `instanceof` check somewhere down the line. It'd make more sense to use a conditional to assign `null` to the variable if it's not the right type.

We might even introduce a helper function to make things easier.

**Comment by ephread** [comment]
We should probably look into [User-defined Type Guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types).

**Comment by y-lohse** [comment]
Yep, and if I'm not mistaken typescript actually has an `as` operator, which might be another option.

**Comment by ephread** [comment]
I think you're right @joethephish, `as` only makes a simple static type assertion which neither cast nor guarantee the type at runtime. (The angle brackets have been changed in favor of `as` because it clashed with some of JSX's assertions IIRC.)

`as` is mostly a hint for the TypeScript compiler and is paradoxically quite rigid (you can't "side-assert", for instance, you cant `as` a `InkObject` into a `INamedContent`). I originally thought that it could make the code look more like C#, but I was overtly excited about it.

To match the C# `as` construct, I wrote the following function which should do the trick (I haven't tested it yet):

```typescript
export function asOrNull<T>(obj: any, type: { new (): T }){
	if (obj instanceof type) {
		return obj as T
	} else {
		return null;
	}
}
```

I have another, very similar function to support the `(type)` cast, which throws instead of returning `null`.

I actually had in mind all the `typeof type ===` logic when I suggested the Type Guards, but @y-lohse  never actually made any mention of this in the original post. I guess I got a bit carried away 😅, sorry!
