### ISSUE TITLE
Better number detection from JSON

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#179]
Would it be possible to replace [this line](https://github.com/ephread/inkjs/blob/master/engine/JsonSerialisation.js#L78-L79) with a simple `typeof token === "number"`? Probably yes.

**Comment by NQNStudios** [comment]
The problem here is that `isNaN()` doesn't translate to querying if something 'is not a number.' It literally just checks if a variable contains JavaScript's wonky `NaN` value for undefined mathematical values like the result of a division by zero.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Description

So a string is not NaN, therefore `!isNaN(str) === true` causing the error where, yes, it looks like JavaScript is saying "\n" is a number.

**Comment by NQNStudios** [comment]
After tracing the source of JTokens and the argument `token`'s original value to JSON.parse called [here](https://github.com/ephread/inkjs/blob/master/engine/Story.js#L60), I'm pretty sure typeof token === 'number'` will do fine. To be extra careful, `typeof token === 'number' && !isNaN(token)` (incredible how messed up JavaScript forces these things to be&mdash;NaN sharing a type with numbers!!)

Not sure how best to test that this is working, but I can make a PR.
