### ISSUE TITLE
SequenceHash implementation

### ISSUE THREAD

**Issue by Glidias** [y-lohse/inkjs#24]
Is building sequenceHash impl in Story.js same as the C# version?
https://github.com/y-lohse/inkjs/blob/master/engine/Story.js#L1205

Your impl doesnt appear to break anything, but I'm wondering Issit the proper way to do it.. The C# version does it as a `int sequenceHash=0; sequenceHash+=c;  // where c is a char`. What exactly happens when you add char to the int var for C#?? I suspect the char is type coerced  to ascii int charcode?  I'm not too sure. Also, is the char-int result added  to the int hash via math addition or contatenated like a string?

**Comment by y-lohse** [comment]
My understanding is that the c is indeed coerced to an ascii value (or some int value anyway), and mathematically added.
Reading the code again, my `parseInt(seqPathStr[i])` probably doesn't do the same. I might look into fixing that.

That being said, the sequenceHash is only used to seed the PRNG. As long as the resulting seed is consistent, it's "right". Since the C# version uses the language built-in PRNG, there is no way to get the exact same result anyway.

**Comment by y-lohse** [comment]
Will be in the next release.
