### ISSUE TITLE
Port the compiler

### ISSUE THREAD

**Issue by y-lohse** [y-lohse/inkjs#3]
This port currently has the engine part ported. Having the compiler (inklecate) would be cool, but it's probably a big endeavour.

**Comment by Immortalin** [comment]
Try [this](http://bridge.net/)

**Comment by Glidias** [comment]
Ever thought of using Haxe? C# and Haxe is very similar and even though I couldn't get a converter to work, converting the runtime codebase manually by hand is a fairly "mindless/trivial" process, with near  Type<T> matching equivalency on just about every line.
Since the inkle codebase do not have any C# specific features like async/await, except for some syntactic sugar like lambdas, and overloaded methods/constructors/delegates...these were simply replaced with explicitly renamed type-checked methods, and internal classes bought out to package level.. Since everything is strictly-type checked when doing a compile, it's easy to track for any mismatched lines, and link them to the respective methods accordingly to get the code compiled successfully) 

The inklecate codebase is slightly larger, but it's just a simple matter of either roping in more manpower to contribute like... "1 file per person", or just take the time accordingly to convert them. It's a boring process, admit-tingly.

**Comment by y-lohse** [comment]
Nope, haven't really considered Haxe. I'm only vaguely familiar with it, though it pops up on my rader every now and then.
To be honest the final js code is quite similar to the C# version — like you said, it was mostly a monotonous process. But Haxe is possibly even closer and the compilation-time type checking seems like something I would have wanted.

But... mostly the same as you; I don't really need the compiler in the browser right now and translating a lot more files isn't too exciting :D.

**Comment by y-lohse** [comment]
@Immortalin I don't have a lot of faith in that kind of tools, although it looks quite profesionnal :stuck_out_tongue: . I don't have visual studio installed but if you'd like to share the output here or in a PR, I'd be more than happy to go through it.

**Comment by Immortalin** [comment]
Blazor WebAssembly

**Comment by Immortalin** [comment]
It's actually not a big endeavour, about a hundred lines:
https://github.com/inkle/ink/blob/master/inklecate/CommandLineTool.cs

**Comment by smwhr** [comment]
FTR : https://github.com/y-lohse/inkjs/pull/931

**Comment by y-lohse** [comment]
It took 6 years almost to the day, but… we have a compiler now \o/
