### ISSUE TITLE
Division is not working as specified

### ISSUE THREAD

**Issue by codeartisticninja** [y-lohse/inkjs#39]
The following ink:

    {2 / 3}
    {7 / 3}
    {1.2 / 0.5}

[should](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-numerical-types-are-implicit) produce:

    0
    2
    2,4

but instead inkjs produces

    0.6666666666666666
    2.3333333333333335
    0

I can understand how inkjs might simply treat all numbers as floats, but that last one puzzles me.. How does 1.2 / 0.5 = 0 ..?

**Comment by y-lohse** [comment]
Hmm, this is the output that I get with the current version:

```
0.6666666666666666
2.3333333333333335
2.4
```

The first two should indeed be ints, so I'll fix that. But I *do* get the correct answer for `{1.2 / 0.5}`. Are you sure you're using the latest version? And did you compile your ink with the latest version of ink?

**Comment by codeartisticninja** [comment]
I just made sure I run the latest stable releases of Inky (0.6.1) and inkjs (1.4.2).. The output is the same as stated in OP..

Also note that the [documentation](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#advanced-numerical-types-are-implicit) says that the results of _all_ math operations (not just division) , where both operands are ints, should be ints (not just rounded floats) as they may eventually end up as a division operand..

    {2 / (3*1.0)} // should result in 0,6666667

**Comment by y-lohse** [comment]
Ah, it appears that inky 0.6.1 doesn't use the latest version of inklecate? @joethephish can you confirm that?

Compiling  `{1.2 / 0.5}` with inky produces `{"inkVersion":15,"root":["G>","ev",1,2.0,0,5.0,"/","out","/ev","G<","\n","done",{"#f":3}]}`, whereas the latest version of inklecate produces `{"inkVersion":15,"root":["G>","ev",1.2,0.5,"/","out","/ev","G<","\n","done",{"#f":3}]}`. Note the `1,2` with a comma instead of a dot in the inky version.

In the meantime, compiling your story with inklecate instead of inky should solve the problem!

**Comment by joethephish** [comment]
Ooouch the damn locale bug again, with rather nasty ramifications it seems. Surprised I failed to include an old version of inklecate in inky. Will fix when I get a mo!

**Comment by y-lohse** [comment]
> Also note that the documentation says that the results of all math operations (not just division) , where both operands are ints, should be ints (not just rounded floats) as they may eventually end up as a division operand..

IIRC, this is already handled as the engine doesn't operate on raw variable,s but converts them to Ints / Floats. And since only a division might cause 2 ints to become a float, the other operations are fine as they are.

*However*, `{2 / (3*1.0)}` is rather nasty. inkjs decides that `1.0` is an integer, which is wrong here. I'll see if I can do a better type detection without breaking anything.

**Comment by joethephish** [comment]
Verified that I hadn't updated Inky with latest locale fixing changes.

New version available here: https://github.com/inkle/inky/releases/tag/0.6.2

**Comment by y-lohse** [comment]
I've looked a bit more into the `1.0` issue, but as far as I can tell there's nothing I can do about it. Javascript just doesn't differentiate between `1` and `1.0`, so I'm afraid this will have to stay as it is.

**Comment by erkyrath** [comment]
There may be a JSON-parsing library that maintains the distinction in some way. I haven't gone looking.

**Comment by curiousdannii** [comment]
If it is important to the Ink language that `1` and `1.0` be distinguished then it really needs to use a different output system. Maybe they should be output as strings, which can the be manually parsed in the various interpreters.
