### ISSUE TITLE
Release version invokes babelHelpers

### ISSUE THREAD

**Issue by erkyrath** [y-lohse/inkjs#47]
When I load ink.min.js, it breaks because it's trying to invoke babelHelpers.classCallCheck(). That's a mistake, right? babelHelpers is listed as a dev dependency only.

**Comment by y-lohse** [comment]
Damnit, that's most most definitely a bug. Looking into it.

**Comment by y-lohse** [comment]
Thanks for the report! I've released a new version [on Github](https://github.com/y-lohse/inkjs/releases/tag/1.4.5) with the fix. I'll publish the new version on npm and bower a bit later today (I'm not on the right machine).

On a sidenote, since Lectrore runs in Electron, I think you'd be perfectly fine using the es2015 version of inkjs :)

I'll leave the issue open because I still need to do some investigation.
If I run all the rollup tasks at once (ie. `grunt rollup`), the babel helpers don't get included in the source files and there are some warnings about a missing `es2015-rollup` preset, despite it being there. However, running the `grunt rollup:legacy` task by itself produces the correct output. It might be a bug with rollup or babel, to be confirmed.

**Comment by erkyrath** [comment]
> I think you'd be perfectly fine using the es2015 version of inkjs

Agreed, but I also like to not change anything without a reason.
