### ISSUE TITLE
External functions get called multiple times

### ISSUE THREAD

**Issue by erbridge** [y-lohse/inkjs#61]
It appears that the following calls `wait` twice - once on each line.

```
Hello world!

{ wait(10000) }

How are you today?
```

The following has the desired effect of only calling `wait` on a single line.

```
Hello world!{ wait(10000) }

How are you today?
```

**Comment by y-lohse** [comment]
Thanks for the report! I haven't looked at the code yet, but it likely happens when the engine is evaluating ahead to find glue.

**Comment by y-lohse** [comment]
Invoking @joethephish for some insight: how is that situation handled in ink? I looked around and didn't see anything outstanding. 
After the first new line is reached, the engine keeps stepping to look for glue, and this triggers the external function call. It eventually finds there is no glue, rewinds, starts playing normally again and triggers the second external call.

**Comment by joethephish** [comment]
Unfortunately, I'm afraid this is intended behaviour, and is a consequence of the way that we handle glue in ink. The basic advice is: **you shouldn't write externals in such a way that they would have side effects**, because of the way ink evaluation works. For more information [see this issue in the main ink repo](https://github.com/inkle/ink/issues/253).

The way we handle this at inkle is by making a custom game-specific parsed line, something simple like `WAIT 1000`, which is read as simple text and parsed by game-side code. We always have a game-specific text parser that turns ink output into game-specific objects anyway, so this is never a problem for us.

Long term, we definitely see that this isn't ideal for many peoples' use cases, so we'd like to solve it properly. But not any time soon I'm afraid - we're trying to hold off on major ink features for now, unless they're needed for Heaven's Vault. Sorry!
