### ISSUE TITLE
Retrieve tags for choices?

### ISSUE THREAD

**Issue by bitbutter** [y-lohse/inkjs#62]
I'm not sure if I'm supposed to be able to do this. What I'd like to is check for the presence of tags on choices in my script so that I can render some choices styled differently.

I haven't been able to figure out how to retrieve tags at the end of choices in my ink script. For instance, if i'd like to check for the presence of the #danger tag to have the third choice styled differently, how could I do that?

```
* Choice one
* Choice two 
* Dangerous choice three #danger
* Choice four
```

**Comment by y-lohse** [comment]
I'm afraid this isn't possible, as far as I know -- in ink.js or otherwise. That `danger` tag will become available once the choice is selected, but not before.
As a workaround, you could create your own "tag syntax" for choices, eg.

```
* Choice one
* Choice two 
* !danger Dangerous choice three
* Choice four
```

...and parse it at run time, as [mentioned here](https://github.com/inkle/ink/issues/239).

**Comment by bitbutter** [comment]
Good to know. Thanks!
