### ISSUE TITLE
ink 0.7.5 update

### ISSUE THREAD

**Issue by joethephish** [y-lohse/inkjs#80]
Not yet released but pending!

Full diff: https://github.com/inkle/ink/compare/0.7.4...0.7.5

**Comment by y-lohse** [comment]
@joethephish Just a head's up, I noticed [`Path. componentCount`](https://github.com/inkle/ink/compare/0.7.4...0.7.5#diff-023e86641747b0b7c33d16bdfa816c30R80) and [`Path.length`](https://github.com/inkle/ink/compare/0.7.4...0.7.5#diff-023e86641747b0b7c33d16bdfa816c30R121) are redundant, not sure if that's intentional.

**Comment by joethephish** [comment]
Not intentional, good catch! Guess I’ll remove componentCount, length is nicer :)
