### ISSUE TITLE
DOC: in the version release and readme, give ink.js path in repo.

### ISSUE THREAD

**Issue by vincentkerdraon** [y-lohse/inkjs#962]
In new versions, I find it always hard to get the latest ink.js file.
In https://github.com/y-lohse/inkjs/releases/tag/v2.1.0, I get the source code, but where can I get the latest ink.js file?

Is it 
- https://github.com/y-lohse/inkjs/blob/master/templates/browser_serverless/ink.js ?
- https://unpkg.com/inkjs@2.1.0/dist/ink-es2015.js ?
- or yet another because these two are outdated ?

Also, the fact that the ink.js does not contain the version doesn't help.
Thank you

**Comment by smwhr** [comment]
I have added a download to the release with the dist files only.

npm (and unpkg) files are also reliable and have the advantage to be hotlinkable if your project is online.

I also have updated the ink.js (and also the story files) in the template so that even if people download them, they end up with the correct ones.
